server:
  port: 80
spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://10.0.16.15:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: hinkleung123
  redis:
    database: 0
    host: 10.0.16.15
    port: 6379
    password: hinkleung